# data stored in /nwb/config.yaml

exec_config:
  do_miguration: true
  create_samples: true
sql_config:
  user: 'root'
  pass: 'password'
  host: 'sql'
  name: 'nwbdb'
  port: 3306
api_config:
  jwtkey: 'examplekeyJWT'
